### ISSUE TITLE
Multiple modifications of requirements

### ISSUE THREAD

**Issue by SpaceInhabitant** [tailoringexpert/web#27]
A requirement can seemingly only be modified once. A second modification is not possible. The edit dialogue opens, but the adaptations to the requirement are not saved. Closing the dialogue is then only possible via the "x" icon without saving the adjustments.
The buttons "SAVE" and "CANCEL" have no functionality.

It is expected that requirements could be modified more than once.

**Comment by baedorf** [comment]
Solved.
Cancel action name fixed, save was fixed with tailoringexpert/plattform#185
